version: '3'
services:
 web:
    image: despesas/despesas-web
    ports: 
      - "3000:3000"
    links:
      - app
 app:
    image: despesas/despesas-app
    ports: 
      - "8081:8081"
    links:
      - db
 db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestao-despesas